keys:
  - &nire-galatea age10dwrrkxcejsla38hfaj95vchr97gg6n0qhld8v2gj2hvntn5xcxqjq5dx2
  - &nire-lysithea age1ss0jcxey4982tdu9lya27wvy4wvzv59t2a9g9w4x57nzpjyrr93q0ljccy
  - &nire-durandal age1yehl5qr2wn28wezhsyzpdfn2gaam9wzgexhgmdnss74zf55t290qdkshnz
creation_rules:
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal
          - *nire-galatea
          - *nire-lysithea
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal
          - *nire-galatea
          - *nire-lysithea
