keys:
  - &nire-lysithea age1ss0jcxey4982tdu9lya27wvy4wvzv59t2a9g9w4x57nzpjyrr93q0ljccy
creation_rules:
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-lysithea
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-lysithea
