keys:
  - &nire-durandal age19klcl9s2vlhnvgae2nhukl2ypwlq0054htgf7jpyxee2wfprmyjqdl7sfg
  - &nire-galatea age10dwrrkxcejsla38hfaj95vchr97gg6n0qhld8v2gj2hvntn5xcxqjq5dx2
  - &nire-lysithea age1t2fu3pdpkvd6lqsk5ckgyyxm556u6dtmvpz4g7yqy7a0nk638c3s3pnrvs
creation_rules:
  - path_regex: _sys.sec.secrets/secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal
          - *nire-galatea
          - *nire-lysithea

  # - path_regex: <user>/secrets.yaml$             # if you want user-specific configs 
    # key_groups:
      # - age:
          # - *nire-durandal
          # - *nire-galatea
          # - *nire-lysithea
