keys:
  - &nire-durandal age19klcl9s2vlhnvgae2nhukl2ypwlq0054htgf7jpyxee2wfprmyjqdl7sfg
creation_rules:
  # - path_regex: ./secrets.yaml$
  - path: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal

  # - path_regex: <user>/secrets.yaml$             # if you want user-specific configs 
    # key_groups:
      # - age:
          # - *nire-durandal
          # - *nire-galatea
          # - *nire-lysithea
