keys:
  - &nire-galatea age10dwrrkxcejsla38hfaj95vchr97gg6n0qhld8v2gj2hvntn5xcxqjq5dx2
creation_rules:
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-galatea
  - path_regex: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-galatea
